# https://ubuntu.com/server/docs/service-nfs

- name: Create mount directory
  ansible.builtin.file:
    path: "{{ debian_mountpoint }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'
  become: true

- name: Mount NFS volume
  ansible.posix.mount:
    src: "{{ nfs_server }}:{{ export_path }}"
    path: "{{ debian_mountpoint }}"
    opts: rw,sync,hard
    state: mounted
    fstype: nfs